"""empty message

Revision ID: 422afdfbe111
Revises: 4ac3c4e05668
Create Date: 2021-12-22 13:31:45.828464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '422afdfbe111'
down_revision = '4ac3c4e05668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=10000), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Notes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Notes',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data', mysql.VARCHAR(length=10000), nullable=True),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.Column('employee_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='Notes_ibfk_1'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('note')
    # ### end Alembic commands ###
